[Interface]
Address = 10.13.13.1
ListenPort = 51820
PrivateKey = QEUq+8AuzVgeByPCQp/kgnO0ynC33alDzdEuWUgitnQ=
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE

[Peer]
# peer1
PublicKey = yhjj6zMn2SWbX+54/GKUZUst76GiKWILDLc4CsoUmnc=
PresharedKey = MhwiMjY4Bokw7SxPNam7RW+sQxOUAyfkTKBRX4spLb0=
AllowedIPs = 10.13.13.2/32

